CREATE TABLE Pessoa (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(20),
    cpf VARCHAR(14) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL,
    sexo VARCHAR(100) NOT NULL,
    cep VARCHAR(9),
    endereco VARCHAR(255),
    numero INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);